spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_review
    password: test
    username: test
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true


